pstore thread_safe fix
jnunemaker/flipper pull request #578
Opened 2021-11-25 15:26 UTC by dpep

not sure the thread_safe attribute is working.  should we save the value, extract it out of @store via `.instance_variable_get`, or delete the accessor since it may not be needed?  (I also sorted the variables to keep things tidy)

2021-11-25 16:32 UTC, bkeepers requested changes
It doesn't look like the attribute reader is used, and I can't think of a scenario when someone would even need to check if it's thread safe or not. I am in favor of just removing it.

I also think the default value should be `true`. [The docs](https://ruby-doc.org/stdlib-3.0.2/libdoc/pstore/rdoc/PStore.html) say there is a minor performance impact, flipper is not write heavy enough to worry about it, and defaulting to `false` could lead to obscure bugs in production.

cc https://github.com/jnunemaker/flipper/pull/334

2021-11-25 19:05 UTC, merged

2021-11-25 19:07 UTC, jnunemaker commented
@bkeepers fixed your stuff in 4048704fefe41b716015294a19a0b94546637630

2021-11-25 19:27 UTC, dpep commented
yeah, I agree that removing the attribute and making pstore thread safe by default are good moves.  it makes Flipper more resilient by default.  we may want to update the changelog since these are technically breaking changes and there's a slight chance of causing trouble for folks downstream

2021-11-25 19:33 UTC, jnunemaker commented
Yep I added a note here: https://github.com/jnunemaker/flipper/blob/6ee7d6309e4d2f30a4380f0a4ef41ffab9fba37a/Changelog.md#L9-L9 That look good?

2021-11-28 15:51 UTC, dpep commented
👍🏻   we may also want to add language around the removal of the `.thread_safe` attribute reader in case folks happen to be using it.  eg https://github.com/jnunemaker/flipper/pull/582